// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5112.JavaClassRobot;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.Jaguar;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.Solenoid;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Talon;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static Solenoid gripperGripperSolenoid;
    public static SpeedController driveTrainLeftFrontMotor;
    public static SpeedController driveTrainRightFrontMotor;
    public static SpeedController driveTrainLeftRearMotor;
    public static SpeedController driveTrainRearRightMotor;
    public static RobotDrive driveTrainRobotDrive;
    public static SpeedController elevatorElevatorMotor;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        gripperGripperSolenoid = new Solenoid(0, 0);
        LiveWindow.addActuator("Gripper", "Gripper Solenoid", gripperGripperSolenoid);
        
        driveTrainLeftFrontMotor = new Talon(2);
        LiveWindow.addActuator("Drive Train", "Left Front Motor", (Talon) driveTrainLeftFrontMotor);
        
        driveTrainRightFrontMotor = new Talon(3);
        LiveWindow.addActuator("Drive Train", "Right Front Motor", (Talon) driveTrainRightFrontMotor);
        
        driveTrainLeftRearMotor = new Talon(1);
        LiveWindow.addActuator("Drive Train", "Left Rear Motor", (Talon) driveTrainLeftRearMotor);
        
        driveTrainRearRightMotor = new Talon(0);
        LiveWindow.addActuator("Drive Train", "Rear Right Motor", (Talon) driveTrainRearRightMotor);
        
        driveTrainRobotDrive = new RobotDrive(driveTrainLeftFrontMotor, driveTrainLeftRearMotor,
              driveTrainRightFrontMotor, driveTrainRearRightMotor);
        
        driveTrainRobotDrive.setSafetyEnabled(true);
        driveTrainRobotDrive.setExpiration(0.1);
        driveTrainRobotDrive.setSensitivity(0.5);
        driveTrainRobotDrive.setMaxOutput(1.0);

        driveTrainRobotDrive.setInvertedMotor(RobotDrive.MotorType.kFrontRight, true);
        driveTrainRobotDrive.setInvertedMotor(RobotDrive.MotorType.kRearRight, true);
        elevatorElevatorMotor = new Jaguar(4);
        LiveWindow.addActuator("Elevator", "Elevator Motor", (Jaguar) elevatorElevatorMotor);
        

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
